# Site settings
title: Eole positive orientation
email: dabinflorent@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's a blog we try to help you about your professional choice with many tips and advices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000"
twitter_username: dabinflorent
github_username:  florentdab
gems: [jekyll-paginate]
paginate: 3 # number of posts I want per page
# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM


